version: '2'
services:
    gogs-web:
        image: gogs/gogs
        # ports:
        #     - "3000:3000"
        volumes:
            - gogs-data:/data
            - ./gogs/app.ini.tmpl:/data/gogs/conf/app.ini.tmpl
            - ./gogs/set_settings.sh:/docker/set_settings.sh
        command: "sh -c '/docker/set_settings.sh'"
        environment:
            - VIRTUAL_HOST=localhost.localdomain
            - PUBLIC_SSH_PORT=22
            - APP_NAME="Gogs Go Git Service"
            - PUBLIC_PROTO=https
            - DISABLE_REGISTRATION=true
    gogs-ssh:
        image: gogs/gogs
        ports:
            - "22:22"
        volumes:
            - gogs-data:/data
            - ./gogs/start_ssh.sh:/docker/start_ssh.sh
        command: "sh -c '/docker/start_ssh.sh'"
    db:
        image: ivlis/alpine-postgres
        environment:
            - POSTGRES_DB=gogs
        volumes:
            - db-data:/var/lib/postgresql/data
    redis:
        image: redis:3-alpine
        command: "redis-server /usr/local/etc/redis/redis.conf"
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
    gogs-data:
    db-data:
